### ISSUE TITLE
GameController should reconnect all lonely neighbours of exploding asteroid

### ISSUE THREAD

**Issue by triszt4n** [poiuztrewq1/projlab_holy_oil#233]
Nice little algorithm for avoiding the possibility of getting stuck at an asteroid without neighbours (also, this is a requirement).

**Comment by vercibar** [comment]
I think this should be done in RemoveAsteroid() function.

**Comment by triszt4n** [comment]
Nice idea. Consider this situation:
![image](https://user-images.githubusercontent.com/60111772/114170135-c526c900-9932-11eb-9b53-a9ee1250d889.png)
A1 explodes, so SunController is getting called with RemoveAsteroid(A1). SunController collects all the lonely asteroidneighbours of A1 and creates a new network between them.
