### ISSUE TITLE
Check and code it, if GameController `CheckXXX` methods are working properly

### ISSUE THREAD

**Issue by triszt4n** [poiuztrewq1/projlab_holy_oil#255]
We should check, if these methods are working properly. If not, code it.

**Comment by bercsenyirihi** [comment]
Tegyük fel hogy 2 egymással nem összekötött aszteroidamezőnk van. Csak az egyikben van szén és csak a másikban van vas mondjuk. Ekkor nem lehet megnyerni mivel nem tudnak a 2 mező közt közlekedni a settlerek vagy bármi de nem hiszem hogy kiszűrik a checkerek. Őszintén nem tudom hogy ezt hogyan tudnám leprogramozni a szomszédság random változtatása nélkül.

**Comment by vercibar** [comment]
Az aszteroidamező nem lehet nem összefüggő játék során. Az AsteroidRepository Remove függvényét lehet hogy bővíteni kell a GameController Generate-jéhez hasonlóan, hogy mindig összefüggő maradjon a gráf.

**Comment by bercsenyirihi** [comment]
Ahogy nézem szinte ugyan az a kód kellene a remove függvénybe is csak fordított sorrendben, előbb ellenőriz aztán ha baj van akkor változtat
