### ISSUE TITLE
Remove skeleton testframework (?)

### ISSUE THREAD

**Issue by triszt4n** [poiuztrewq1/projlab_holy_oil#266]
We do not need the skeleton package from our project anymore, only the Logger class from it.

We can remove those, as we already have a tag at the skeleton's last commit: https://github.com/poiuztrewq1/projlab_holy_oil/releases/tag/vSkeleton

This way, the projects filelist gets shorter and the source lighter.

**Comment by poiuztrewq1** [comment]
APPROVED
